server:
  port: 8088

spring:
  application:
    name: eureka-zuul

zuul:
  # 路由前缀
  prefix: /api
  # 声明路由
  routes:
    xxx-service: /manage/**
    search-server: /search/**
    user-server: /user-center/**
    oauth-server: /oauth/**
    car-server: /car/**
    order-server: /order/**
    pay-server: /pay/**
    sale-server: /sale/**
    miaosha-service: /miaosha/**
#    # 路由名称
#    api-xxx:
#      # 声明将所有以/api-ribbon/的请求都转发到eureka-ribbon的服务中
#      path: /api-xxx/**
#      serviceId: xxx-service
#    search-xxx:
#      path: /api-search/**
#      serviceId: search-server
  # 启用重试
  retryable: true
  # 包含此路径的不进行路由
  ignored-patterns: -/manage/**
    #-/upload/**

  # 忽略上传服务
  ignored-services:
    -upload-server
  #将域名加到请求头中
  add-host-header: true
  # set-cookie被zull禁止了，将这个属性设置为空，代表启动 set-cookie
  sensitive-headers:

#配置负载
ribbon:
  ConnectTimeout: 30000     # 连接超时时间(ms)
  ReadTimeout: 120000   # 通信超时时间(ms)
  OkToRetryOnAllOperations: true # 是否对所有操作重试
  MaxAutoRetriesNextServer: 2 # 同一服务不同实例的重试次数
  MaxAutoRetries: 1 # 同一实例的重试次数

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 120000 # 熔断超时时长：6000ms

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

mrshop:
  #声明不进行拦截的请求用,分隔
  filter:
    excludes: /api/oauth/oauth/login,/api/user-center/user/register,/api/search/es/search,/api/oauth/oauth/verify,/api/manage/category/list,/api/order/order/getOrderInfoByUserId,/api/miaosha/miaosha/createUserOrderWithMq


  jwt:
    pubKeyPath: D:\\Users\\rea.pub # 公钥地址(私钥加密,公钥解密)
    cookieName: MRSHOP_TOKEN