server:
  port: 8900  #端口号

spring:
  application:
    name: pay-server  #服务名称

#日志设置
logging:
  level:
    #打印与我们相关的日志信息
    com.baidu.shop: debug
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

mrshop:
  worker:
    workerId: 1 # 项目唯一标识
    datacenterId: 1 # 序列号 其实也是唯一标识
  jwt:
    pubKeyPath: D:\Users\rea.pub # 公钥地址
    cookieName: MRSHOP_TOKEN # cookie的名称